removeListener method has been deprecated
Since `removeListener` is deprecated (https://reactnative.dev/docs/keyboard#removelistener) we are getting the error below:

`TypeError: _reactNative.Keyboard.removeListener is not a function. (In '_reactNative.Keyboard.removeListener(keyboardShowEvent, onKeyboardWillShow)', '_reactNative.Keyboard.removeListener' is undefined)`